This is my first git project for docker.
# To add a repository to git

#git remote add origin  https://github.com/otunetta2011/docker-docs.git

#git remote -v(to verify)

#git push --set-upstream origin master(to set the origin to master)

#git push orgigin master(to push to your github)

#git remote remove(rm) origin(to delete ur repository)



